author: FreezeJ
description: FreezeJ's blog
keyword: Linux,Python,Network,DevOps
favicon: 

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
 Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: true

# qrcode
qrcode: true

# comment
# you can set gitment, uyan or disqus

comment: gitment

# gitment config
gitment_owner: FreezeJ
gitment_repo: FreezeJ.github.io
gitment_oauth_id: e454d874578e161854c4
gitment_oauth_secret: d52121a2ee21be59da10cbb323649596989eb512


# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id: 

# disqus config
disqus_shortname: 

about: 
  banner: http://file.muyutech.com/about.jpg
  avatar: https://avatars0.githubusercontent.com/u/26806873?v=4
  description: "热爱技术 热爱生活"
  # weibo_username: 
  # twitter_username: 
  github_username: FreezeJ
  zhihu_username: freezej
  music163_userid: 101976455
  # douban_username: yanm1ng
  # linkedin_username:

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML
